### ISSUE TITLE
Image upload not working with flutter web using sendbird_sdk 3.1.11

### ISSUE THREAD

**Issue by lathamios** [sendbird/sendbird-sdk-flutter#36]
Hi I have tried uploading an attachment using flutter web and it fails:

1. `import 'package:universal_io/io.dart';`

Is missing from `lib/screens/channel/components/attachment_modal.dart`

Even with that added I get an error: 

```

Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:59134/dart_sdk.js:5067:11)
    at Function.new (http://localhost:59134/packages/universal_io/src/io/sync_socket.dart.lib.js:3589:19)
    at _showPicker (http://localhost:59134/packages/sendbird_flutter/screens/channel/components/attachment_modal.dart.lib.js:180:31)
    at _showPicker.next (<anonymous>)
    at http://localhost:59134/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:59134/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:59134/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:59134/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:59134/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:59134/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59134/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:59134/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:59134/dart_sdk.js:40714:13)
    at http://localhost:59134/dart_sdk.js:36191:9

```

**Comment by intoxicated** [comment]
Hi @lathamios, we will look into this soon. Thanks for your patient.

**Comment by lathamios** [comment]
Hi - Thanks -  I should have left this on the other repository you have: https://github.com/sendbird/Sendbird-Flutter, my apologies

**Comment by lathamios** [comment]
**UPDATE**

There's a bug with this package allows file upload via the web:

universal_io: 

So when trying to convert a Uint8List into a File using the function File.fromRawPath(bytes), it returns:

```
Error: FormatException: Unexpected extension byte (at offset 0)

```

Ideally for web upload it would be great to have a function to upload a file not as a File but  as a MultipartFile

**Comment by lathamios** [comment]
Guys, any update on this?
